name: Build Check

on:
  push:
    branches:
      - '*'

  pull_request:
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Run Install
        run: |
          pnpm install

      - name: Lint Check
        run: |
          pnpm lint

      - name: Package Build Check - Headless
        run: |
          pnpm -F headless build

      - name: Package Build Check - Date Picker
        run: |
          pnpm -F date-picker build

      - name: Website Build Check
        run: |
          pnpm build
