name: Build Check

on:
  push:
    branches:
      - '*'

  pull_request:
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Install
        run: |
          yarn

      - name: Lint Check
        run: |
          yarn lint

      - name: Package Build Check - Headless
        run: |
          cd packages/headless
          yarn
          yarn build
          cd ../..

      - name: Package Build Check - Date Picker
        run: |
          cd packages/date-picker
          yarn
          yarn build
          cd ../..

      - name: Website Build Check
        run: |
          yarn build
