name: Code Check

on:
  push:
    branches:
      - '*'

  pull_request:
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Install
        run: |
          yarn

      - name: Lint Check
        run: |
          yarn lint

      - name: Package Build Check - Date Picker
        run: |
          yarn build

      - name: Package Build Check - User Manual
        run: |
          yarn build:manual
